name: Comprobar archivos grandes
on: [push]
jobs:
    check_large_files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Buscar archivos mayores de 1 MB
              run: |
                  echo "Buscando archivos grandes..."
                  find . -type f -size +1M -print || echo "No se encontraron archivos grandes."
