name: Formato Prettier
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Prettier
        run: npm install -g prettier

      - name: Comprobar formato
        run: prettier . --check || echo "Hay archivos con problemas de formato"

