name: Info del Repo
on: [push]
jobs:
    mostrar_info:
        runs-on: ubuntu-latest
        steps:
            - name: Imprimir informaci√≥n
              run: |
                  echo "Repositorio: ${{ github.repository }}"
                  echo "Usuario: ${{ github.actor }}"
                  echo "Rama: ${{ github.ref }}"
